name: action-manager-backend service ci

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/action-manager-backend-ci.yaml"
      - ".github/workflows/reusable-backend-service-ci.yaml"
      - "services/action-manager-app/**"
      - "parent-pom/**"
      - "base-platform/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/action-manager-backend-ci.yaml"
      - ".github/workflows/reusable-backend-service-ci.yaml"
      - "services/action-manager-app/**"
      - "parent-pom/**"
      - "base-platform/**"
      
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  ci:
    uses: ./.github/workflows/reusable-backend-service-ci.yaml
    with:
      service-name: "action-manager-backend"
      service-path: "services/action-manager-app/action-manager-backend"
      sonar-project-key: "hvantran_action-manager-app"
      docker-image-name: "action-manager-backend"
      jacoco-enabled: true
      build-native: true
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
