name: action-manager-backend service ci

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/action-manager-backend-ci.yaml"
  pull_request:
    branches: [ "main" ]
    paths:
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/action-manager-backend-ci.yaml"
      
  workflow_dispatch:

jobs:
  Sonar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0
      - uses: ./.github/workflows/actions
      - name: Analyze with sonar cloud
        env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn clean install sonar:sonar -Dsonar.projectKey=hvantran_parent-pom -f parent-pom &&
          mvn clean install -DskipTests sonar:sonar -Dsonar.projectKey=hvantran_base-platform -f base-platform &&
          mvn clean install -DskipTests -f base-platform/common-apps/springboot-common-app &&
          mvn clean install -Ddockerfile.skip=true -DskipTests sonar:sonar -Dsonar.projectKey=hvantran_action-manager-app -f services/action-manager-app
  
