name: action-manager-ui service ci

env:
   CI: false

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/action-manager-ui-ci.yaml"
  pull_request:
    branches: [ "main" ]
    paths:
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/action-manager-ui-ci.yaml"
      
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0
      - uses: ./.github/workflows/actions
      - name: Run maven build
        run: |
          mvn clean install -DskipTests -P prod -f parent-pom &&
          mvn clean install -DskipTests -P prod -f base-platform &&
          mvn clean install -DskipTests -P prod -f services/action-manager-app/action-manager-ui
      #- name: Analyze with sonar cloud
      #  env:
      #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #  run: |
      #    mvn sonar:sonar -Dsonar.projectKey=hvantran_parent-pom -f parent-pom;
      #    mvn sonar:sonar -Dsonar.projectKey=hvantran_base-platform -f base-platform;
      #    mvn sonar:sonar -Dsonar.projectKey=hvantran_action-manager-ui -f services/action-manager-ui

  #Unit-Tests:
  #  needs: Build
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v3
  #      with:
  #        submodules: recursive
  #        token: ${{ secrets.ACCESS_TOKEN }}
  #        fetch-depth: 0
  #    - uses: ./.github/workflows/actions
  #    - run: yarn test
  #    - name: Unit test results
  #      uses: dorny/test-reporter@v1
  #      if: failure()
  #      with:
  #        name: Unit-Test-Results
  #        path: "services/action-manager-app/action-manager-ui/**/surefire-reports/*.xml"
  #        reporter: jest-junit
  #        fail-on-error: true
  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0
      - uses: ./.github/workflows/actions
      - name: Run maven package
        run: mvn clean package -DskipTests -P prod -f services/action-manager-app/action-manager-ui
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./services/action-manager-app/action-manager-ui
          file: ./services/action-manager-app/action-manager-ui/Dockerfile
          push: true
          tags: tranvanhoa2810/action-manager-ui:1.0.${{github.run_number}}
