name: action-manager-backend service ci

env:
  CI: false

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/action-manager-backend-ci.yaml"
  pull_request:
    branches: [ "main" ]
    paths:
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/action-manager-backend-ci.yaml"
      
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0
      - uses: ./.github/workflows/actions
      - name: Run maven build
        run: |
          mvn clean install -f parent-pom &&
          mvn clean -f base-platform dependency:tree &&
          mvn clean install -Ddockerfile.skip=true -DskipTests -P prod -f base-platform &&
          mvn clean -f services/action-manager-app/action-manager-backend dependency:tree &&
          mvn clean install -Ddockerfile.skip=true -DskipTests -P prod -f services/action-manager-app/action-manager-backend

  Test:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0
      - uses: ./.github/workflows/actions
      - name: Run maven test
        run: |
          mvn clean install -f parent-pom && 
          mvn clean install -Ddockerfile.skip=true -DskipTests -P prod -f base-platform &&
          mvn clean install -Dmaven.test.failure.ignore=true -P test -f services/action-manager-app/action-manager-backend
      - name: Unit test results
        uses: dorny/test-reporter@v1
        if: failure()
        with:
          name: Unit-Test-Results
          path: "services/action-manager-app/action-manager-backend/**/surefire-reports/*.xml"
          reporter: java-junit
          fail-on-error: true
      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: services/action-manager-app/action-manager-backend/target/site/jacoco/
      - name: Jacoco Badge Generator
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: services/action-manager-app/action-manager-backend/target/site/jacoco/jacoco.csv
  Sonar:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0
      - uses: ./.github/workflows/actions
      - name: Analyze with sonar cloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn clean install -f parent-pom &&
          mvn clean install -Ddockerfile.skip=true -DskipTests -f base-platform &&
          mvn clean install -Ddockerfile.skip=true -DskipTests -Dsonar.qualitygate.wait=true -Dsonar.projectKey=hvantran_action-manager-app sonar:sonar -f services/action-manager-app
  Deploy:
    needs: Sonar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0
      - uses: ./.github/workflows/actions
      - name: Run maven package
        run: |
          mvn clean install -f parent-pom && 
          mvn clean install -Ddockerfile.skip=true -DskipTests -P prod -f base-platform
      - uses: actions/upload-artifact@v4
        with:
          name: action-manager-backend
          path: services/action-manager-app/action-manager-backend/**/*.jar
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set VERSION environment variable
        run: |
          echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Build and push
        run: |
          mvn clean install -Ddockerfile.skip=true -DskipTests -P native -f services/action-manager-app/action-manager-backend spring-boot:build-image
          docker tag action-manager-backend:${{ env.VERSION }} ${{ secrets.DOCKERHUB_USERNAME }}/action-manager-backend:latest
          docker tag action-manager-backend:${{ env.VERSION }} ${{ secrets.DOCKERHUB_USERNAME }}/action-manager-backend:1.0.${{github.run_number}}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/action-manager-backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/action-manager-backend:1.0.${{github.run_number}}
