name: ecommerce-stats-app service ci

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/ecommerce-stats-app-ci.yaml"
  pull_request:
    branches: [ "main" ]
    paths:
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/ecommerce-stats-app-ci.yaml"
      
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0
      - uses: ./.github/workflows/actions
      - name: Run maven build
        run: |
          mvn clean install -Ddockerfile.skip=true -DskipTests -P prod -f parent-pom &&
          mvn clean -f base-platform dependency:tree &&
          mvn clean install -Ddockerfile.skip=true -DskipTests -P prod -f base-platform &&
          mvn clean -f base-platform/common-apps/system-health-statistics dependency:tree &&
          mvn clean install -Ddockerfile.skip=true -DskipTests -P prod -f base-platform/common-apps/system-health-statistics &&
          mvn clean -f base-platform/common-apps/springboot-common-app dependency:tree &&
          mvn clean install -Ddockerfile.skip=true -DskipTests -P prod -f base-platform/common-apps/springboot-common-app &&
          mvn clean -f services/ecommerce-stats-app dependency:tree &&
          mvn clean install -Ddockerfile.skip=true -DskipTests -P prod -f services/ecommerce-stats-app
      #- name: Analyze with sonar cloud
      #  env:
      #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #  run: |
      #    mvn sonar:sonar -Dsonar.projectKey=hvantran_parent-pom -f parent-pom;
      #    mvn sonar:sonar -Dsonar.projectKey=hvantran_base-platform -f base-platform;
      #    mvn sonar:sonar -Dsonar.projectKey=hvantran_ecommerce-stats-app -f services/ecommerce-stats-app

  Unit-Tests:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0
      - uses: ./.github/workflows/actions
      - name: Run maven test
        run: |
          mvn clean install -DskipTests -P test -f parent-pom && 
          mvn clean install -Ddockerfile.skip=true -DskipTests -P prod -f base-platform &&
          mvn clean install -Ddockerfile.skip=true -DskipTests -P prod -f base-platform/common-apps/system-health-statistics &&
          mvn clean install -Ddockerfile.skip=true -DskipTests -P prod -f base-platform/common-apps/springboot-common-app &&
          mvn clean install -Dmaven.test.failure.ignore=true -P test -f services/ecommerce-stats-app
      - name: Unit test results
        uses: dorny/test-reporter@v1
        if: failure()
        with:
          name: Unit-Test-Results
          path: "services/ecommerce-stats-app/**/surefire-reports/*.xml"
          reporter: java-junit
          fail-on-error: true
  Deploy:
    needs: Unit-Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.3
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0
      - uses: ./.github/workflows/actions
      - name: Run maven package
        run: |
          mvn clean install -Ddockerfile.skip=true -DskipTests -P prod -f parent-pom && 
          mvn clean install -Ddockerfile.skip=true -DskipTests -P prod -f base-platform &&
          mvn clean install -Ddockerfile.skip=true -DskipTests -P prod -f base-platform/common-apps/system-health-statistics &&
          mvn clean install -Ddockerfile.skip=true -DskipTests -P prod -f base-platform/common-apps/springboot-common-app &&
          mvn clean install -Ddockerfile.skip=true -DskipTests -P prod -f services/ecommerce-stats-app
      - uses: actions/upload-artifact@v3
        with:
          name: ecommerce-stats-app
          path: services/ecommerce-stats-app/**/*.jar
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./services/ecommerce-stats-app/target
          file: ./services/ecommerce-stats-app/target/classes/Dockerfile
          push: true
          tags: tranvanhoa2810/ecommerce-stats-app:latest
