name: endpoint-collector-ui service ci

env:
   CI: false

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/endpoint-collector-ui-ci.yaml"
  pull_request:
    branches: [ "main" ]
    paths:
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/endpoint-collector-ui-ci.yaml"
      
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0
      - uses: ./.github/workflows/actions
      - name: Run maven build
        run: |
          mvn clean install -DskipTests -P prod -f parent-pom &&
          mvn clean install -DskipTests -P prod -f base-platform &&
          mvn clean install -DskipTests -P prod -f services/external-endpoint-collector/endpoint-collector-ui
      #- name: Analyze with sonar cloud
      #  env:
      #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #  run: |
      #    mvn sonar:sonar -Dsonar.projectKey=hvantran_parent-pom -f parent-pom;
      #    mvn sonar:sonar -Dsonar.projectKey=hvantran_base-platform -f base-platform;
      #    mvn sonar:sonar -Dsonar.projectKey=hvantran_endpoint-collector-ui -f services/endpoint-collector-ui

  #Unit-Tests:
  #  needs: Build
  #  runs-on: ubuntu-latest
  #  steps:
  #    - uses: actions/checkout@v4
  #      with:
  #        submodules: recursive
  #        token: ${{ secrets.ACCESS_TOKEN }}
  #        fetch-depth: 0
  #    - uses: ./.github/workflows/actions
  #    - run: yarn test
  #    - name: Unit test results
  #      uses: dorny/test-reporter@v1
  #      if: failure()
  #      with:
  #        name: Unit-Test-Results
  #        path: "services/external-endpoint-collector/endpoint-collector-ui/**/surefire-reports/*.xml"
  #        reporter: jest-junit
  #        fail-on-error: true
  Deploy:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0
      - uses: ./.github/workflows/actions
      - name: Run maven package
        run: mvn clean package -DskipTests -P prod -f services/external-endpoint-collector/endpoint-collector-ui
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses:  docker/build-push-action@v5
        with:
          context: ./services/external-endpoint-collector/endpoint-collector-ui
          file: ./services/external-endpoint-collector/endpoint-collector-ui/Dockerfile
          push: true
          tags: tranvanhoa2810/endpoint-collector-ui:latest,tranvanhoa2810/endpoint-collector-ui:1.0.${{github.run_number}}
