name: Project Management All Services CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: hvantran/project-management/.github/workflows/common@main
      - name: Run Maven build command
        run: mvn clean install -DskipTests
        
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: hvantran/project-management/.github/workflows/common@main
      - name: Run Maven test command
        run: mvn test
