name: assigned-issues-are-in-progress
on:
  issues:
    types:
      - assigned
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    name: Move to In Progress Column
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.3
        with:
          project: Action Manager Backlog
          column: In Progress
          repo-token: ${{ secrets.ACCESS_TOKEN }}
