name: assigned-issues-are-in-progress
on:
  issues:
    types:
      - assigned
jobs:
  move-assigned-card:
    runs-on: ubuntu-latest
    name: Move to In Progress Column
    steps:
      - uses: alex-page/github-project-automation-plus@7ffb872c64bd809d23563a130a0a97d01dfa8f43
        with:
          project: Project Management
          column: In Progress
          repo-token: ${{ secrets.ACCESS_TOKEN }}
