name: spring-cloud-gateway-app service ci

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/spring-cloud-gateway-app-ci.yaml"
      - ".github/workflows/reusable-base-platform-service-ci.yaml"
      - "base-platform/common-apps/spring-cloud-gateway-app/**"
      - "parent-pom/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - ".github/workflows/actions/action.yaml"
      - ".github/workflows/spring-cloud-gateway-app-ci.yaml"
      - ".github/workflows/reusable-base-platform-service-ci.yaml"
      - "base-platform/common-apps/spring-cloud-gateway-app/**"
      - "parent-pom/**"
      
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  ci:
    uses: ./.github/workflows/reusable-base-platform-service-ci.yaml
    with:
      service-name: "spring-cloud-gateway-app"
      service-path: "base-platform/common-apps/spring-cloud-gateway-app"
      docker-image-name: "spring-cloud-gateway-app"
      docker-context: "./base-platform/common-apps/spring-cloud-gateway-app/target"
      dockerfile-path: "./base-platform/common-apps/spring-cloud-gateway-app/target/classes/Dockerfile"
    secrets:
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
