name: project management ci

env: 
  CI: false
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0
      - uses: ./.github/workflows/actions
      - name: Run Maven Build Command
        run: mvn clean install -Ddockerfile.skip=true -DskipTests -P prod

  Test:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0
      - uses: ./.github/workflows/actions
      - name: Run Maven Test Command
        run: mvn test -Dmaven.test.failure.ignore=true -P test
      - name: Unit Test Results
        uses: dorny/test-reporter@v1
        with:
          name: Unit-Test-Results
          path: "**/surefire-reports/*.xml"
          reporter: java-junit
          fail-on-error: false

  Sonar:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0
      - uses: ./.github/workflows/actions
      - name: Analyze with sonar cloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn clean install sonar:sonar -Dsonar.qualitygate.wait=true -Dsonar.projectKey=hvantran_parent-pom -f parent-pom &&
          mvn clean install -Ddockerfile.skip=true -DskipTests sonar:sonar -Dsonar.qualitygate.wait=true -Dsonar.projectKey=hvantran_base-platform -f base-platform
