name: project management ci

env: 
  CI: false
  
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0
      - uses: ./.github/workflows/actions
      - name: Configure npm auth for GitHub Packages
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: echo "//npm.pkg.github.com/:_authToken=${ACCESS_TOKEN}" >> ~/.npmrc
      - name: Run Maven Build Command
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: mvn clean install -Ddockerfile.skip=true -DskipTests -P prod
      - name: Run Maven Test Command
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: mvn test -Dmaven.test.failure.ignore=true -P test
      - name: Unit Test Results
        uses: dorny/test-reporter@31a54ee7ebcacc03a09ea97a7e5465a47b84aea5 # v1.9.1
        with:
          name: Unit-Test-Results
          path: "**/surefire-reports/*.xml"
          reporter: java-junit
          fail-on-error: false
          fail-on-empty: false
      - name: Analyze with sonar cloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          mvn sonar:sonar -Dsonar.qualitygate.wait=true -Dsonar.projectKey=hvantran_project-management
